version: '3'
services:
    redis:
        image: "redis:alpine"
        ports:
            - 16379:6379

    stastd:
        image: prom/statsd-exporter
        ports:
            - 9125:9125
            - 9102:9102

    grafana:
        image: grafana/grafana
        ports:
            - 3000:3000
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=foobar
            - GF_USERS_ALLOW_SIGN_UP=false

    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "5672:5672"

    experiment_manager:
        image: osabuoun/experiment_manager
        #image: experiment_manager
        ports:
            - "8778:8777"