version: '2'
services:
    redis:
        image: "redis:alpine"
        ports:
            - 6379:6379
        networks:
            jef-network:

    stastd:
        image: prom/statsd-exporter
        ports:
            - 9125:9125
            - 9125:9125/udp
            - 9102:9102
            - 9102:9102/udp
        networks:
            jef-network:

    grafana:
        image: grafana/grafana
        ports:
            - 3000:3000
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=foobar
            - GF_USERS_ALLOW_SIGN_UP=false
        networks:
            jef-network:

    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "5672:5672"
        networks:
            jef-network:

    prometheus:
        image: prom/prometheus
        volumes:
            - ./prometheus/:/etc/prometheus/
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
            - 19090:9090
        networks:
            jef-network:

    experiment_manager:
        image: osabuoun/experiment_manager
        #image: experiment_manager
        ports:
            - "8777:8777"
        networks:
            jef-network:
networks:
    jef-network:
        external: true     