version: '2'
services:
    redis:
        image: "redis:alpine"
        ports:
            - 16379:6379
    stastd:
        image: prom/statsd-exporter
        container_name: statsd
        ports:
            - 9125:9125
            - 3102:9102
    
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        volumes:
            - ./config/prometheus/:/etc/prometheus/
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
        ports:
            - 9091:9090

    grafana:
        image: grafana/grafana
        depends_on:
            - prometheus
        ports:
            - 3000:3000
        volumes:
            - ./data/grafana:/var/lib/grafana
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=foobar
            - GF_USERS_ALLOW_SIGN_UP=false

    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "5673:5672"

    jqueuing_manager:
        image: osabuoun/jqueuing_manager
        #image: jqueuing_manager
        volumes:
            - ./data/jqueuing_manager/:/data
            - /usr/bin/docker:/usr/bin/docker
            - /var/run/docker.sock:/var/run/docker.sock
        links:
            - rabbit
            - redis
        depends_on:
            - rabbit
            - redis
        ports:
            - "5599:5599"

    experiment_manager:
        image: osabuoun/experiment_manager
        #image: experiment_manager
        volumes:
            - ./data/experiment_manager/:/data
        links:
            - redis
        depends_on:
            - redis
        ports:
            - "8777:8777"